const names=require('./4-names')
const sayHi=require('./5-utils')
console.log(names)
const data=require('./6-alternative_flavor')
console.log(data)
require('./7-mind_grenade')

sayHi('susan')
sayHi(names.john)
sayHi(names.peter)